### ISSUE TITLE
Robust Cholesky decomposition option

### ISSUE THREAD

**Issue by jknowles** [ggopalan/FastGP#1]
Hi @ggopalan 

Thanks for this great package. I have a package, https://github.com/jknowles/merTools, which simulates prediction intervals for multilevel models by making thousands of draws from a multivariate normal distribution, and this code has helped me speed up that functionality tremendously. 

One problem I run into is that occasionally the variance-covariance matrix I am simulating from is not positive-definite and there is a need for a robust implementation of the Cholesky decomposition similar to the functionality of the normal `chol()` function in R. 

I read up on the Eigen library a bit and found out that using `ldlt()` instead of `llt()` would provide me with what I was after. This introduces a performance hit, but it also makes the function produce output when it runs into one of these matrices. For my application this is the desired behavior. 

I wanted to share the code I used to do this: 

````c++
//[[Rcpp::export]]
Eigen::MatrixXd rcppeigen_get_chol(const Eigen::Map<Eigen::MatrixXd> & A){
  Eigen::MatrixXd chol = A.ldlt().matrixL();
  return chol;
}
````

I wanted to ask if either a) you would consider adding this option to the package somehow, or b) if you would mind me including this code with my package and citing FastGP as the inspiration and you as the author of the `rcppeigen_get_chol` function in its original form. 

Let me know which you prefer. Thanks for this great work -- I spent a long time googling around how to make faster draw from a multivariate normal before I came across this, which suited my needs perfectly.

**Comment by ggopalan** [comment]
Hi Jared,

Thanks for making my day with a really nice message! It's really wonderful
to hear that this package has been useful to you. It's funny how such a
common routine, i.e., sampling from a MVN, can be such a computational
bottleneck sometimes, and I think Dirk has done a great job with Rcpp and
RcppEigen for making this easier.

Many thanks for finding this optimization. If you don't mind, since it is a
small tweak, I would prefer to add this additional function to the package.
It shouldn't be difficult and take probably a day or two max. Also I would
like to acknowledge you as the individual for helping optimize the package
as well.

Does that sound fair to you?

Best,
Giri

**Comment by jknowles** [comment]
That sounds great. I'd rather import your package and credit you instead of maintaining essentially a tiny fork of your function over the long run.

I don't know if you prefer to implement this change as an option to the rcpp_eigen_get_chol() function (something like pivot = TRUE), or if you want to right a secondary function. I leave that decision up to you -- I don't know if there would be performance problems one way or the other. If you let me know, I can submit a pull request doing it the way you like. 

I am testing the performance speedup that this has added to my package right now and I'll be happy to report that publicly to direct people to this package. I like that it is lightweight and easy to debug, while still being very fast.

**Comment by jknowles** [comment]
This appears fixed as well. I'll be happy to report back to you the speed increase I found with my package as a result of this work.
